# This is confing for PostgreSQL - Uncomment if you want to use this Persistence Engine
GeneralConfig:
  pooling_time: 60
  author: "vizaard"

PersistenceConfig:
  # This is confing for PostgreSQL - Uncomment if you want to use this Persistence Engine
  persistence: postgresql
  connection_string: "dbname=snooplyze user=postgres password=postgresql host=127.0.0.1 port=5432"

  # This is confing for DuckDB - Uncomment if you want to use this Persistence Engine
  #persistence: duckdb
  #db_file_path: C:\code\vizaard.duckdb

  # This is confing for SQLite - Uncomment if you want to use this Persistence Engine
  #persistence: sqlite
  #db_file_path: C:\code\vizaard.sqlite

  # This is confing for MySQL - Uncomment if you want to use this Persistence Engine
  #persistence: mysql
  #host: 127.0.0.1
  #port: 3306
  #user: root
  #password: mysql
  #database: snooplyze

NotificationConfig:
  - notification_type: console
  - notification_type: flatfile
    file_path: C:\code\snooplyze.txt
  - notification_type: email
    email_address: XXX
    email_password: XXX
    recipients: XXX
