# This is confing for PostgreSQL - Uncomment if you want to use this Persistence Engine
Config:
  - persistence: postgresql
    connection_string: "dbname=snooplyze user=postgres password=postgresql host=127.0.0.1 port=5432"
  - pool_time: 60
# This is confing for DuckDB - Uncomment if you want to use this Persistence Engine
#Config:
#  - persistence: duckdb
#    db_file_path: viz.duckdb
#  - pool_time: 60

# This is confing for Microsoft SQL Server - Uncomment if you want to use this Persistence Engine
# WARNING - this hasn't been implemented yet!
#Config:
#  - persistence: mssql
#    connection_string: MYSQLSUPERINSTANCE
#    database_name: vizdb
#  - pool_time: 120
