# This is confing for PostgreSQL - Uncomment if you want to use this Persistence Engine
GeneralConfig:
  pool_time: 60
  author: "vizaard"

PersistenceConfig:
  # This is confing for PostgreSQL - Uncomment if you want to use this Persistence Engine
  persistence: postgresql
  connection_string: "dbname=snooplyze user=postgres password=postgresql host=127.0.0.1 port=5432"

# This is confing for DuckDB - Uncomment if you want to use this Persistence Engine
#  persistence: duckdb
#  db_file_path: C:\code\vizaard.duckdb

# This is confing for Microsoft SQL Server - Uncomment if you want to use this Persistence Engine
# WARNING - this hasn't been implemented yet!
#  persistence: mssql
#  connection_string: MYSQLSUPERINSTANCE
#  database_name: vizdb

NotificationConfig:
  - notification_type: console
  - notification_type: email
    email_address: adad@wp.pl
    subject: "alter"
